### ISSUE TITLE
Command line parameter not being escaped correctly, can't handle spaces in path

### ISSUE THREAD

**Issue by bording** [adamralph/min-ver#41]
I was trying out the alpha package and hit a problem:

```
C:\Users\Brandon\.nuget\packages\minver\1.0.0-alpha.3\build\MinVer.targets(12,5): error MSB3073: The command "dotnet C:\Users\Brandon\.nuget\packages\minver\1.0.0-alpha.3\build\MinVer.Cli.dll C:\Users\Brandon\Documents\Visual Studio 2017\Projects\ConsoleApp141\ConsoleApp141 > "obj\Debug\netcoreapp2.1\min-ver-879a2.txt"" exited with code -532462766.
```

```
Unhandled Exception: System.Exception: Path 'C:\Users\Brandon\Documents\Visual' doesn't point at a valid workdir.
   at MinVer.Versioner.GetVersion(String path) in C:\projects\min-ver\MinVer\Versioner.cs:line 21
   at MinVer.Cli.Program.Main(String[] args) in C:\projects\min-ver\MinVer.Cli\Program.cs:line 14
```

Looks like the parameters being passed to the `dotnet` command in the targets file need to be updated to account for potential spaces in the paths.

**Comment by adamralph** [comment]
Thanks for catching this. Would you like to send a PR?

**Comment by bording** [comment]
@adamralph Done: #44
